# @format

name: MySQL + Koa2 Server + Vue3 todolist

on:
  push:
    branches: [main] # 监听main分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 制作docker镜像并推送到dockerhub
      - name: build and push docker image
        run: |
          docker login -u ${{ secrets.ALIYUNCS_PASSWORD }} -p ${{ secrets.ALIYUNCS_PASSWORD }}
          docker-compose build
          docker-compose push
          docker logout
