# @format

name: MySQL + Koa2 Server + Vue3 todolist

on:
  push:
    branches: [master] # 监听main分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 制作docker镜像并推送到dockerhub
      - name: build and push docker image
        run: |
          docker login --username=${{ secrets.ALIYUNCS_USERNAME }} --password=${{ secrets.ALIYUNCS_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker-compose build
          docker-compose push
          docker logout
